### ISSUE TITLE
no utils

### ISSUE THREAD

**Issue by YYY-12138** [YLTun/federated_diffusion_model#1]
In the code, I cannot find utils files but there is "import utils"...

**Comment by YYY-12138** [comment]
In the code, I cannot find utils files but there is "import utils"...
And I try importing utils from different packages, but it didn't work.  
So, I guess it was created by the author himself.
Can you update it and I'll appreciate it very much.

**Comment by YLTun** [comment]
Hi, I have added the missing file.
