### ISSUE TITLE
Request for missing diffusion.py file and implementation details in Federated Learning and Diffusion code

### ISSUE THREAD

**Issue by FlappyWG** [YLTun/federated_diffusion_model#2]
Hello, I am interested in Federated Learning and Diffusion models, and I have been searching for code that combines the two. However, I have had difficulty finding it. Luckily, I came across your code on Github, which I found to be very valuable for learning and reference. However, I noticed that the diffusion.py file is missing from the code. Would you be able to upload the missing diffusion file, or alternatively, could you explain how the "sampler" and "diffusion loss" are implemented in this code?

**Comment by YLTun** [comment]
Hi, I have added the missing file.
